Server:
  bind_address: '0.0.0.0'  #Ipv4 for binding http server, ex. 127.0.0.1 or 0.0.0.0
  port: 8800 #Port for binding http server, be carefull about permissions on different port
  refresh_time: 2 #Prometheus endpoint update time, in seconds, ex. 2

Global:
  unit: 'ms'

Local:
  src_addr: '0.0.0.0' 
  timeout: 1
  ttl: 64
  size: 56

Services:
  - name: 'service01'
    device: 'simplesla-local'
    target: '127.0.0.1'
    delay: 20
