server:
  bind_address: '0.0.0.0'  #Ipv4 for binding http server, ex. 127.0.0.1 or 0.0.0.0
  port: 8800 #Port for binding http server, be carefull about permissions on different port
  refresh_time: 2 #Prometheus endpoint update time, in seconds, ex. 2

global:
  unit: 'ms'

local:
  src_addr: '0.0.0.0' 
  timeout: 1
  ttl: 64
  size: 56

devices:
  - name: 'RT'
    type: 'cisco'
    transport: 'telnet'
    address: '10.10.10.1'
    username: 'admin'
    password: 'cisco'
    port: 23

policies:
  - name: mypolicy
    max_rtt: 0.15
    
services:
  - name: 'service01'
    device: 'simplesla-local'
    target: '192.168.0.2'
    delay: 3
    policy: mypolicy
  - name: 'service02'
    device: 'simplesla-local'
    target: '172.16.0.2'
    delay: 7
  - name: 'testcisco'
    device: 'RT'
    target: '10.10.10.2'
    delay: 4


