version: '3.5'

networks:
  simplesla-network:
    driver: bridge

services:
  simple-sla:
    image: "ghcr.io/northpowered/simple-sla:latest"
    container_name: simple-sla
    restart: always
    environment:
      - SSLA_LL=INFO
    ports:
     - "8800:8800"
    volumes:
      - ./config.yml:/app/config.yml
    networks:
      - simplesla-network
