name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - name: Build and publish the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/northpowered/simple-sla:latest
        docker run ghcr.io/northpowered/simple-sla:latest
        docker push ghcr.io/northpowered/simple-sla:latest
